authors = ["ScottPJones <scottjones@alum.mit.edu>"]
desc = "API for Str and Chr types"
keywords = ["API", "Strings", "Characters"]
license = "MIT"
name = "StrAPI"
uuid = "69e7dfc3-c4d0-5e14-8d95-d6042a05b383"

[deps]
Pkg     = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test    = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random  = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

ModuleInterfaceTools = "5cb8414e-7aab-5a03-a681-351269c074bf" # x13gh7y6id3fbmke
