name = "StrAPI"
desc = "API for Str and Chr types"
authors = ["ScottPJones <scottjones@alum.mit.edu>"]
keywords = ["API", "Strings", "Characters"]
license = "MIT"
uuid = "7309dffa-5f6c-11e8-0bac-7b275211ca99"
repo = "https://github.com/JuliaString/StrAPI.jl.git"
git-tree-sha1 = "ee8eeb3b8a3bbff685c38c4815fb3b8b4c3538ee"
version = "0.1.1"
#deps = ["ModuleInterfaceTools", "Random"]
